<a href="https://colab.research.google.com/github/VefaKosova/Machine-Learning/blob/main/Complete_Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
from time import process_time

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0012465130000003377


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time2 = process_time()

np_array += 5

end_time2 = process_time()

print(end_time2 - start_time2)

0.00019896199999980269


In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,2,3,4),(1,2,3,4)])
print(b)

[[1 2 3 4]
 [1 2 3 4]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(1,2,3,4)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [ ]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
b = np.random.random((3,4))
print(b)

[[0.36544075 0.80657619 0.18070234 0.3634492 ]
 [0.49315441 0.036817   0.81930442 0.09600172]
 [0.86390178 0.53682597 0.83967931 0.55870609]]


In [ ]:
c = np.random.randint(10,100,(3,5))
print(c)

[[50 49 30 12 82]
 [63 38 81 21 90]
 [17 64 56 67 50]]


In [ ]:
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]
